version: '3'
services:
  vue:
    build: ./npcite-vue
    ports:
      - "1000:80"
  springboot:
    image: openjdk:18-jdk
    volumes:
      - "./npCite-0.0.1-SNAPSHOT.jar:/web/npCite-0.0.1-SNAPSHOT.jar"
    working_dir: /web
    command: java -jar npCite-0.0.1-SNAPSHOT.jar
  mysql:
    restart: always
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./schema.sql:/schema.sql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: npCite